CREATE TABLE `AplikasiSurvey`(`id` int NOT NULL AUTO_INCREMENT, `Nama/Inisal` varchar(50) NULL DEFAULT NULL, `Umur` varchar(50) NULL DEFAULT NULL, `Tanggal Kunjungan` date NULL DEFAULT NULL, `Waktu Kunjungan` time NULL DEFAULT NULL, `Poli` varchar(50) NULL DEFAULT NULL, `Kritik` varchar(500) NULL DEFAULT NULL, `Saran` varchar(500) NULL DEFAULT NULL, `Foto` varchar(500) NULL DEFAULT NULL, PRIMARY KEY (`id`))CHARACTER SET utf8;
CREATE TABLE `aplikasisurveyuggroups`(`GroupID` int NOT NULL AUTO_INCREMENT, `Label` varchar(300) NULL DEFAULT NULL, `Provider` varchar(10) NULL DEFAULT '', `Comment` mediumtext NULL DEFAULT NULL, PRIMARY KEY (`GroupID`))CHARACTER SET utf8;
CREATE TABLE `aplikasisurveyugmembers`(`UserName` varchar(255) NOT NULL, `GroupID` int NOT NULL, `Provider` varchar(10) NOT NULL DEFAULT '', PRIMARY KEY (`UserName`(50),`GroupID`,`Provider`(10)))CHARACTER SET utf8;
CREATE TABLE `aplikasisurveyugrights`(`TableName` varchar(255) NOT NULL, `GroupID` int NOT NULL, `AccessMask` varchar(10) NULL DEFAULT NULL, `Page` mediumtext NULL DEFAULT NULL, PRIMARY KEY (`TableName`(50),`GroupID`))CHARACTER SET utf8;
CREATE TABLE `user`(`id` int NOT NULL AUTO_INCREMENT, `user` varchar(50) NULL DEFAULT NULL, `pasword` varchar(50) NULL DEFAULT NULL, `Level` varchar(50) NULL DEFAULT NULL, PRIMARY KEY (`id`))CHARACTER SET utf8;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `AplikasiSurvey` (`id`,`Nama/Inisal`,`Umur`,`Tanggal Kunjungan`,`Waktu Kunjungan`,`Poli`,`Kritik`,`Saran`,`Foto`) VALUES (5,'g','n','1937-10-15','04:00:00','umum','mmn',' nnn','');
INSERT INTO `AplikasiSurvey` (`id`,`Nama/Inisal`,`Umur`,`Tanggal Kunjungan`,`Waktu Kunjungan`,`Poli`,`Kritik`,`Saran`,`Foto`) VALUES (6,'nanna','mamam','2031-05-12','00:00:00','nnn','bbxbxb','bzbzb','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `aplikasisurveyuggroups` (`GroupID`,`Label`,`Provider`,`Comment`) VALUES (1,'users','',NULL);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `aplikasisurveyugmembers` (`UserName`,`GroupID`,`Provider`) VALUES ('admin',-1,'');
INSERT INTO `aplikasisurveyugmembers` (`UserName`,`GroupID`,`Provider`) VALUES ('user',1,'');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('<global>',-1,'ADESPIM',NULL);
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('admin_members',-1,'ADESPIM',NULL);
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('admin_rights',-1,'ADESPIM',NULL);
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('admin_users',-1,'ADESPIM',NULL);
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('aplikasisurvey',-1,'ADESPIM',NULL);
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('aplikasisurvey',1,'AES','');
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('user',-1,'ASM','');
INSERT INTO `aplikasisurveyugrights` (`TableName`,`GroupID`,`AccessMask`,`Page`) VALUES ('user',1,'A','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `user` (`id`,`user`,`pasword`,`Level`) VALUES (1,'admin','123456','administrator');
INSERT INTO `user` (`id`,`user`,`pasword`,`Level`) VALUES (2,'user','123456','users');
SET FOREIGN_KEY_CHECKS = 1;
